### ISSUE TITLE
LC & TC

### ISSUE THREAD

**Issue by RasitEvduzen** [LimHaeryong/eskf-gnss-imu-localization#1]
Hello Lim,

I hope you are doing well. This repository is very beneficial for navigation. I have a question: Did you opt for a loosely or tightly coupled approach when implementing this algorithm?

**Comment by LimHaeryong** [comment]
Hello Rasit,

https://www.mathworks.com/help/nav/ug/ground-vehicle-pose-estimation-for-tightly-coupled-imu-gnss.html

According to above link, My implementation is loosely coupled approach because it receives the position and velocity of the ego vehicle from the GNSS subscriber.

**Comment by RasitEvduzen** [comment]
Hello Lim,
Thank you for the information.
